function Hd = standardFilter(varargin)
%standardFilter return a lowpass filter with the default passband and
%stopband being 250Hz and 350Hz respectively

if nargin==0
    Fpass = 250;    % Passband Frequency
    Fstop = 350;    % Stopband Frequency
elseif nargin==1
    Fpass=varargin{1};
    Fstop=Fpass+100;
elseif nargin==2
    Fpass=varargin{1};
    Fstop=varargin{2};
end

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 19-Mar-2018 15:58:09


Apass = 1;      % Passband Ripple (dB)
Astop = 60;     % Stopband Attenuation (dB)
Fs    = 20000;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

% Hd=design(h,'equiripple');
% with DSP system toolbox
Hd = design(h, 'equiripple', ...
    'MinOrder', 'any', ...
    'StopbandShape', 'flat');
end